### PR TITLE
Port to Swift 3

### PR DESCRIPTION
**Pull request by JJC1138**
Hello. Thank you so much for making this library. It's exactly what I wanted except that I'm working on a project using Swift 3 at the moment so I've ported the library to the latest Swift 3 (Preview 6) syntax. I made it work on the new `Data` struct rather than `NSData` so it's a bit more Swifty (although they're convertible to each other of course).

I appreciate that Swift 3 is still a moving target at this point with lots of changes in each beta so it probably wouldn't make sense to merge it to your master branch, but perhaps you could merge it to a new branch on your repo and we could document in the README that both versions are available?

Thanks again!

### CODE REVIEW

**Comment by ServicePal** [comment]
Excellent work Jon. I applaud your work. We plan to move to the Swift 3.0 in a few months, so much appreciated.

**Comment by JJC1138** [comment]
@ServicePal Oh thanks for letting me know. I'm glad it's useful 😊

**Comment by JJC1138** [comment]
Just to note, this PR is compatible with the final Swift 3.0 release (no changes were needed)

**Comment by leemorgan** [comment]
Thanks for making these changes Jon!

**Comment by JJC1138** [comment]
Oh cool, thank you for merging! 😊

**Pull request merged**
